### ISSUE TITLE
API request for all people in SKBL

### ISSUE THREAD

**Issue by salgo60** [spraakbanken/skbl-portal#22]
I try to get WIkidata in synch with SKBL and need to get an API call that returns all person articles

I use: this [url](https://ws.spraakbanken.gu.se/ws/karp/v5/minientry?q=extended%7C%7Cand%7Cnamn%7Cexists&mode=skbllinks&show=name%2Curl&sort=sorteringsnamn.sort%2Csorteringsnamn.init%2Ctilltalsnamn.sort&size=10000&resource=skbl)

but I am not sure I get all the people 

See my try in a [Jupyter Notebook](https://github.com/salgo60/open-data-examples/blob/master/Svenskt%20Kvinnobiografiskt%20lexikon.ipynb)

Regards
Magnus Sälgö
0705937579
salgo60@msn.com
twitter: [salgo60](https://twitter.com/salgo60)

**Comment by salgo60** [comment]
In this [notebook](https://github.com/salgo60/open-data-examples/blob/master/Svenskt%20Kvinnobiografiskt%20lexikon.ipynb) I haver a query [getting all people](https://ws.spraakbanken.gu.se/ws/karp/v5/minientry?q=extended%7C%7Cand%7Cnamn%7Cexists&mode=skbllinks&show=name%2Curl&sort=sorteringsnamn.sort%2Csorteringsnamn.init%2Ctilltalsnamn.sort&size=10000&resource=skbl).... in SKBL 

In another [Notebook](https://github.com/salgo60/open-data-examples/blob/master/Svenskt%20Kvinnobiografiskt%20lexikon%20part%203.ipynb) I compare SKBL and SBL but needs published date how do I write a query getting all SKBL women with fields 
- ** publishedDate** 
-  the name of the author  
  -- article_author_lastname
  -- article_author_firstname
Right now I loop all records and retrieved the data which --> 1600 calls instead of 1 

Regards
Magnus Sälgö
0705937579
salgo60@msn.com

**Comment by kod-kristoff** [comment]
Hi!

To get all women from the backend use this call (without aliases for):
https://ws.spraakbanken.gu.se/ws/karp/v5/query?mode=skbl&q=extended||and|skblstatus|equals|ok&size=10000

You will get a JSON-object back that has the following structure:
```
{
  "hits": {
    "hits": [ length = min( size in query, matching number of documents )
      {
        "_source": { actual entry
           "article_author": [
              { "firstname": "X", "lastname": "Y" },
              ...
           ],
           ...
            "publication_date": "YYYY-MM-DD",
           ...
        }
      },
      ...
    ],
    "total": number telling you the number of matching documents for this query (may be larger than the length of hits.hits
}
```

I hopes this helps, please ask more if anything is unclear!

**Comment by salgo60** [comment]
Tackar det blev 
*  19 sekunder vs. 290 sekunder
*  1 anrop vs. 1600

Nu passerar SKBL 1500 artiklar om min snurra funkar 

![image](https://user-images.githubusercontent.com/14206509/93499884-d915c980-f913-11ea-84ca-d5ca3c7a6ecd.png)
