### ISSUE TITLE
Förslag till rättelse (skbl.se) -> Error communicating with target host. -> 421 4.2.1 Unable to connect'

### ISSUE THREAD

**Issue by salgo60** [spraakbanken/skbl-portal#24]
Skickar jag in en **Förslag till rättelse**

Fås efter några timmar 

    Leveransen till följande mottagare eller grupper är försenad:
    skbl@history.gu.se
    
    Ämne: Förslag till rättelse (skbl.se)
    
    Det här meddelande har inte levererats än. Fler försök att leverera kommer att göras.
    
    Servern kommer att försöka leverera meddelandet inom 1 dagar, 19 timmar och 55 minuter. Du meddelas om meddelandet inte har kunnat levereras inom den tiden._
    Diagnostisk information för administratörer:
    
    Genererande server: GUEXC02-P.GU.GU.SE
    Mottagande server: dag02-176 (10.240.64.47)
    
    skbl@history.gu.se
    Server at dag02-176 (10.240.64.47) returned '400 4.4.7 Message delayed'
    2020-09-21 14:14:58 - Server at dag02-176 (10.240.64.47) returned '451 4.4.397 Error communicating with target host. -> 421 4.2.1 Unable to connect'
    
    Ursprungshuvuden:
    
    Received: from GUEXC02-P.GU.GU.SE (10.240.64.41) by GUEXC02-P.GU.GU.SE
     (10.240.64.41) with Microsoft SMTP Server (version=TLS1_2,
     cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id 15.1.1979.3; Mon, 21
     Sep 2020 12:15:17 +0200
    Received: from esa1.hc487-47.eu.iphmx.com (207.54.76.178) by
     GUEXC02-P.GU.GU.SE (10.240.64.41) with Microsoft SMTP Server (version=TLS1_2,
     cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id 15.1.1979.3 via
     Frontend Transport; Mon, 21 Sep 2020 12:15:16 +0200
    IronPort-SDR: m6ROtnaUMOlFpjak9j2xKjQBMXhwx93wD010YwIc7kLvNyyzzpiJ718ZLm5d7pODglL8iXYqlp
    u3AoKfgNcDl5Ev9eKKrtX3EihYejm/qFR9h3lrj70LV2T29TVdXtD+DzmGPclJh+vPAKJGS8hA
    Y2dxZWhuv60xg67k9p1TLqvxDY4e5sEUjyi537L2KfC3vcy6fRajtQ6gmYhCZr9srxOY3x9N9L
    fnytMDxW/nscBkdyVm92eS3BoruLQSY6szA5Mn3+5ibsunICapPFa4tTrA7ndKyiEhL3iN/t/Y
    j8k=

**Comment by salgo60** [comment]
![image](https://user-images.githubusercontent.com/14206509/94005445-94b87c80-fd9e-11ea-8536-da09f86ca57c.png)

**Comment by anne17** [comment]
Det här har att göra med kraschen av GUs mailservrar: http://driftinfo.gu.se/
Vi kan inte göra något annat än att vänta på att GUs IT-enhet fixar problemen.

**Comment by salgo60** [comment]
Ok då. hoppas vi på dom.,,,,
