### ISSUE TITLE
Samma som SKBL

### ISSUE THREAD

**Issue by salgo60** [spraakbanken/skbl-portal#25]
På mötet  2020-sep-9 pratade vi om att se om det går att ha Samma som **Wikidata Qnummer**

Idag publicerades [MonaLisaEnglund.json](https://skbl.se/sv/artikel/MonaLisaEnglund.json) som är syskon till Ulla Britt Englund [UllaBrittEnglund.json](https://www.skbl.se/sv/artikel/UllaBrittEnglund.json)

det borde framgå att systern är samma som **SKBL UllaBrittEnglund** i er JSON på samma sätt som vi pratade om samma som [Wikidata Q100323738](https://www.wikidata.org/wiki/Q100323738?uselang=sv) [json](https://www.wikidata.org/wiki/Special:EntityData/Q100323738.json) en variant som jag tror på är att även ange att relationen syskon är samma som WIkidata [Property:P3373](https://www.wikidata.org/wiki/Property:P3373) 

hur det ser ut idag i SKNL
![image](https://user-images.githubusercontent.com/14206509/95856538-7836b100-0d5a-11eb-97c3-ba91db86036a.png)

* på MonaLisaEnglund = [Q4943626](http://www.wikidata.org/entity/Q4943626) [json](http://www.wikidata.org/entity/Q4943626.json) anger vi det i Wikidata som [P3373](https://www.wikidata.org/wiki/Property:P3373) är [Wikidata Q100323738](https://www.wikidata.org/wiki/Q100323738?uselang=sv) 

![image](https://user-images.githubusercontent.com/14206509/96361980-62decf80-112a-11eb-9e2a-a9797d7666fc.png)

Tog upp detta med att koppla ihop domäner på bästa sett [video vid 48:40](https://youtu.be/o2AqQkw7nug?t=2901) så en variant är att ni anger att eran egen egenskap är samma som  [P3373](https://www.wikidata.org/wiki/Property:P3373) så blir det mer maskinläsbart

**Comment by kod-kristoff** [comment]
@salgo60 Hej Magnus! SKBL-projektet har löpt ut, så det kommer inte hända så mycket med detta inom den närmaste framtiden tyvärr...

**Comment by salgo60** [comment]
@kod-kristoff tackar har anat det ;-) 

Min reflektion vad som kunde gjorts bättre
* historiska yrken samma som andra arkiv
  * kollar jag på historiska yrken så har SKBL en snygg beskrivning men skall svenskt kulturarv bli digitalt så behöver olika institutioner etc. prata ihop sig idag är det enormt spretigt se https://github.com/salgo60/HISCOKoder 
* ny möjlighet [Wikibase.cloud](https://twitter.com/salgo60/status/1454826049066479620?s=20) som rel. enkelt löser samma som och skapa en egen "SKBL" eller "Litteraturbanken" kunskapsgraf
  * Wikidata som skulle kunna bli en Hub som kopplar ihop kulturarv med vad en crowdsourced plattform som Wikipedia gör kommer från nyår ha en gratis version [Wikibase.cloud](https://twitter.com/salgo60/status/1454826049066479620?s=20) som är en tom Wikidata där man rel enkelt skulle kunna skapa en egen variant typ Litterturbanken Wikibase... 
* Bättre flöde mellan olika system önskas
  * exempel tankar hur Litteraturbanken <-> LIBRISXL <-> Wikidata sträva efter att alla Litterturbankens författare finns hos alla 3 och att vi skall kunna skicka källor som länkade data se https://github.com/salgo60/spa2Commons/issues/3
