### ISSUE TITLE
Felaktiga årtalsangivelser (typografi) på hela sajten

### ISSUE THREAD

**Issue by jroxendal** [spraakbanken/skbl-portal#3]
På svenska är det korrekta att skriva yyyy–yyyy (med n-dash och utan mellanslag). På sajten används mellanslag plus m-dash. 

http://www.prefix.nu/siffror-och-tal.html (rubriken 'tidsperiod').

**Comment by anne17** [comment]
Det nuvarande formatet följer redaktionens önskemål.

**Comment by jroxendal** [comment]
👎
